### ISSUE TITLE
Deadlock with the remove implementation

### ISSUE THREAD

**Issue by bnicolae** [zhangshun97/Lock-free-Red-black-tree#2]
The remove implementation seems to deadlock. I've attached the data.txt input for which this issue is present.
[data.txt](https://github.com/zhangshun97/Lock-free-Red-black-tree/files/5279771/data.txt)

**Comment by zhangshun97** [comment]
Hi there,

I just run experiment with the data file you provided and it seems working well as follows.
```
-bash-4.2$ ./test_parallel
total_size: 100000
time taken by insert with 1 threads and sleep 0 seconds: 5.624497sec
time taken by remove with 1 threads and sleep 0 seconds: 5.658925sec
time taken by insert with 2 threads and sleep 0 seconds: 2.844980sec
time taken by remove with 2 threads and sleep 0 seconds: 2.898992sec
time taken by insert with 4 threads and sleep 0 seconds: 1.452575sec
time taken by remove with 4 threads and sleep 0 seconds: 1.476045sec
time taken by insert with 8 threads and sleep 0 seconds: 0.734743sec
time taken by remove with 8 threads and sleep 0 seconds: 0.760226sec
time taken by insert with 16 threads and sleep 0 seconds: 0.363444sec
time taken by remove with 16 threads and sleep 0 seconds: 0.384236sec
```
I know several successful experiments don't mean that there will not be a potential deadlock.
But also, I don't find any potential deadlock on my side and it's also hard to repeat the 'deadlock' you mentioned by just looking at the data file or just experimenting with it.
It will be very helpful if you could provide the exact situation (of the tree) and the operation the program is taking that lead to the 'deadlock' you mentioned.
There are some functions will help printing out the tree in file `src/utils.cpp`. You could manually invoke these functions when using gdb to debug. But it will be really hard to interpret the output if the tree is too big (at the moment when 'deadlock' happens).

As for me, since the whole program is using CAS operation and we have already discussed about the deadlock caused by two threads being too 'close' to each other and how we address such problem in our report. So personally, I don't think there is a deadlock. Maybe you can provide more information about your local experiments including your hardware environment, software environment or anything you find through tools like gdb.

Anyway, I really appreciate your interest in our project.

**Comment by zhangshun97** [comment]
Issue closed due to conversation timeout :)

**Comment by ADSWT518** [comment]
Hi, I also encountered this problem. But when I tried it again, everything is ok :joy:

![image](https://user-images.githubusercontent.com/58338486/129659463-01fc04cf-9662-4590-b4e2-77b3878eafa7.png)

Here is my data file:

[data.txt](https://github.com/zhangshun97/Lock-free-Red-black-tree/files/6996880/data.txt)

By the way, this project is great! It helps me a lot to understand this paper. Thank you a lot!
